import json, subprocess, concurrent.futures as cf

urls = {
"figma": "https://mcp.figma.com/mcp",
"gitlab": "https://gitlab.com/api/v4/mcp",
"egnyte": "https://mcp-server.egnyte.com/mcp",
"honeycomb": "https://mcp.honeycomb.io/mcp",
"jotform": "https://mcp.jotform.com/",
"lucid": "https://mcp.lucid.app/mcp",
"lusha": "https://mcp.lusha.com/mcp",
"make": "https://mcp.make.com",
"microsoft-learn": "https://learn.microsoft.com/api/mcp",
"mux": "https://mcp.mux.com",
"newrelic": "https://mcp.newrelic.com/mcp",
"pandadoc": "https://mcp.pandadoc.com/v1/mcp",
"prisma": "https://mcp.prisma.io/sse",
"sanity": "https://mcp.sanity.io",
"statsig": "https://api.statsig.com/v1/mcp",
"todoist": "https://ai.todoist.net/mcp",
"wix": "https://mcp.wix.com/sse",
"smartbear-bugsnag": "https://bugsnag.mcp.smartbear.com/mcp",
"chilipiper": "https://fire.chilipiper.com/api/fire-edge/v1/org/mcp",
"apify": "https://mcp.apify.com/",
"airbyte": "https://mcp.airbyte.ai/mcp",
"exa": "https://mcp.exa.ai/mcp",
"clerk": "https://mcp.clerk.com/mcp",
"cloudinary": "https://asset-management.mcp.cloudinary.com/mcp",
"composio": "https://connect.composio.dev/mcp",
"courier": "https://mcp.courier.com",
"grafana": "https://mcp.grafana.com/mcp",
"huggingface": "https://huggingface.co/mcp",
"serpapi": "https://mcp.serpapi.com/mcp",
"supabase": "https://mcp.supabase.com/mcp",
"miro": "https://mcp.miro.com/",
"teamwork": "https://mcp.ai.teamwork.com",
"thoughtspot": "https://agent.thoughtspot.app/mcp",
"lovable": "https://mcp.lovable.dev",
"zapier": "https://mcp.zapier.com/api/mcp/mcp",
"plaid": "https://api.dashboard.plaid.com/mcp/sse",
"stytch": "https://mcp.stytch.dev/mcp",
"telnyx": "https://api.telnyx.com/v2/mcp",
"dialpad": "https://mcp.dialpad.com/mcp",
"hunter": "https://mcp.hunter.io/mcp",
"jam": "https://mcp.jam.dev/mcp",
"netlify": "https://netlify-mcp.netlify.app/mcp",
"invideo": "https://mcp.invideo.io/sse",
"heroku": "https://mcp.heroku.com/mcp",
"render": "https://mcp.render.com/mcp",
"digitalocean": "https://mcp.digitalocean.com/mcp",
"aws-knowledge": "https://knowledge-mcp.global.api.aws",
"postman": "https://mcp.postman.com/minimal",
"incident.io": "https://mcp.incident.io/mcp",
"rootly": "https://mcp.rootly.com/sse",
"buildkite": "https://mcp.buildkite.com/mcp",
"semrush": "https://mcp.semrush.com/v1/mcp",
"mailchimp": "https://mcp.mailchimp.com/",
"canny": "https://mcp.canny.io/mcp",
"helpscout": "https://mcp.helpscout.com/mcp",
"knock": "https://mcp.knock.app/mcp",
"onesignal": "https://mcp.onesignal.com/mcp",
"zoho": "https://mcp.zoho.com/mcp",
"smartsheet": "https://mcp.smartsheet.com/mcp",
"shortcut": "https://mcp.shortcut.com/mcp",
"moderntreasury": "https://mcp.moderntreasury.com/mcp",
"intercom-x": "https://mcp.intuit.com/mcp",
"deepwiki": "https://mcp.deepwiki.com/mcp",
"context7": "https://mcp.context7.com/mcp",
"tavily": "https://mcp.tavily.com/mcp/",
"firecrawl": "https://mcp.firecrawl.dev/v2/mcp",
"brightdata": "https://mcp.brightdata.com/mcp",
"pipedream": "https://remote.mcp.pipedream.net",
"vanta": "https://mcp.vanta.com/mcp",
"atlan": "https://mcp.atlan.com/mcp",
"workato": "https://mcp.workato.com/mcp",
"fellow": "https://mcp.fellow.app/mcp",
"productboard": "https://mcp.productboard.com/mcp",
"gitbook": "https://mcp.gitbook.com/mcp",
"zendesk-": "https://mcp.zendesk.com/mcp",
"salesforce-": "https://mcp.salesforce.com/mcp",
"calendly-": "https://mcp.calendly.com/mcp",
"docusign-": "https://mcp.docusign.com/mcp",
"typeform-": "https://mcp.typeform.com/mcp",
"chargebee-": "https://mcp.chargebee.com/mcp",
"ramp-": "https://mcp.ramp.com/mcp",
"brex-": "https://mcp.brex.com/mcp",
"deel-": "https://mcp.deel.com/mcp",
"gusto-": "https://mcp.gusto.com/mcp",
"greenhouse-": "https://mcp.greenhouse.io/mcp",
"ashby-": "https://mcp.ashbyhq.com/mcp",
"pipedrive-": "https://mcp.pipedrive.com/mcp",
"zoominfo-": "https://mcp.zoominfo.com/mcp",
"freshworks-": "https://mcp.freshworks.com/mcp",
"front-": "https://mcp.frontapp.com/mcp",
"gorgias-": "https://mcp.gorgias.com/mcp",
"loops-": "https://mcp.loops.so/mcp",
"launchdarkly-": "https://mcp.launchdarkly.com/mcp",
"algolia-": "https://mcp.algolia.com/mcp",
"snowflake-": "https://mcp.snowflake.com/mcp",
"fivetran-": "https://mcp.fivetran.com/mcp",
"dbt-": "https://mcp.getdbt.com/mcp",
"sigma-": "https://mcp.sigmacomputing.com/mcp",
"contentful-": "https://mcp.contentful.com/mcp",
"iterable-": "https://mcp.iterable.com/mcp",
"braze-": "https://mcp.braze.com/mcp",
"customerio-": "https://mcp.customer.io/mcp",
"segment-": "https://mcp.segment.com/mcp",
"okta-": "https://mcp.okta.com/mcp",
"1password-": "https://mcp.1password.com/mcp",
"drata-": "https://mcp.drata.com/mcp",
"carta-": "https://mcp.carta.com/mcp",
"mercury-": "https://mcp.mercury.com/mcp",
"bill-": "https://mcp.bill.com/mcp",
"navan-": "https://mcp.navan.com/mcp",
"expensify-": "https://mcp.expensify.com/mcp",
"qualtrics-": "https://mcp.qualtrics.com/mcp",
"surveymonkey-": "https://mcp.surveymonkey.com/mcp",
"aha-": "https://mcp.aha.io/mcp",
"dovetail-": "https://mcp.dovetail.com/mcp",
"gainsight-": "https://mcp.gainsight.com/mcp",
"salesloft-": "https://mcp.salesloft.com/mcp",
"outreach-": "https://mcp.outreach.io/mcp",
"docebo-": "https://mcp.docebo.com/mcp",
"personio-": "https://mcp.personio.com/mcp",
"hibob-": "https://mcp.hibob.com/mcp",
"bamboohr-": "https://mcp.bamboohr.com/mcp",
"rippling-": "https://mcp.rippling.com/mcp",
"lattice-": "https://mcp.lattice.com/mcp",
"clio-": "https://mcp.clio.com/mcp",
"ironclad-": "https://mcp.ironcladapp.com/mcp",
"spotdraft-": "https://mcp.spotdraft.com/mcp",
"juro-": "https://mcp.juro.com/mcp",
}

init = json.dumps({"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"probe","version":"1.0"}}})

def probe(name, url):
    try:
        p = subprocess.run(["curl","-sk","-o","/dev/null","-D","-","--max-time","12",
            "-X","POST","-H","Content-Type: application/json","-H","Accept: application/json, text/event-stream",
            "--data",init,url], capture_output=True, text=True, timeout=20)
        head = p.stdout
        lines = head.splitlines()
        status = lines[0] if lines else "NOCONN"
        www = next((l for l in lines if l.lower().startswith("www-authenticate")), "")
        return name, url, status.strip(), www.strip()[:160]
    except Exception as e:
        return name, url, "ERR "+str(e)[:40], ""

with cf.ThreadPoolExecutor(30) as ex:
    for name,url,status,www in ex.map(lambda kv: probe(*kv), urls.items()):
        print(f"{name}\t{status}\t{www}\t{url}")
