// AUTO-GENERATED from the "Agent Library" spreadsheet — do not edit by hand;
// regenerate when the source changes. 116 starter agents.
//
// Each entry is a clickable starter: clicking it pre-fills the New Agent form,
// and the Tembo Coding Agent expands `task` into a full spec. `categories`
// (see connection-categories.ts) drive connection-aware ranking + chips.

import type { ConnectionCategory } from "@/lib/connection-categories";

export type LibraryAgent = {
  id: string;
  title: string;
  task: string;
  workArea: string;
  buildOrder: number;
  categories: ConnectionCategory[];
  labels: string[];
  firstWave: boolean;
  impact: number;
  resistance: number;
  score: number;
  sizeFit: string;
  verticalFit: string;
  /** Original spreadsheet Connection(s) phrasing, shown as a caption. */
  connectionSummary: string;
  notes?: string;
};

export const AGENT_LIBRARY: LibraryAgent[] = [
  {id:"crm-hygiene-nudge",title:"CRM hygiene nudge",task:"Flag opportunities missing stage, value, or close date; ping the rep in Slack",workArea:"Sales / SDR",buildOrder:1,categories:["crm","notify"],labels:["Flag"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read (Slack notify)",notes:"Double win: visible cleanup plus it repairs the data the rest of the library depends on"},
  {id:"speed-to-lead-monitor",title:"Speed-to-lead monitor",task:"Inbound lead sits un-actioned past X minutes; nudge the rep",workArea:"Sales / SDR",buildOrder:2,categories:["crm","notify"],labels:["Nudge"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read (Slack notify)",notes:"Speed-to-lead is a top revenue lever"},
  {id:"new-lead-enrichment",title:"New-lead enrichment",task:"On a new record, research and write a summary into it",workArea:"Sales / SDR",buildOrder:3,categories:["crm","enrichment"],labels:["Summary"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM + one enrichment source",notes:"Saves prep on every lead"},
  {id:"post-call-follow-up-draft",title:"Post-call follow-up draft",task:"Turn a call into a drafted follow-up the rep sends",workArea:"Sales / SDR",buildOrder:4,categories:["recorder","email"],labels:["Draft"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Recorder to email draft",notes:"Draft-only keeps the human in the loop"},
  {id:"quote-pricing-lookup",title:"Quote / pricing lookup",task:"Answer rep pricing and config questions from the price book",workArea:"Sales / SDR",buildOrder:5,categories:["docs"],labels:["Q&A"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Price book read",notes:"Read-only knowledge agent"},
  {id:"competitor-battlecard-surface",title:"Competitor battlecard surface",task:"Surface the right battlecard when a competitor is named on a deal",workArea:"Sales / SDR",buildOrder:6,categories:["docs"],labels:["Flag"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS, Services",connectionSummary:"Knowledge base read"},
  {id:"lost-deal-reason-capture",title:"Lost-deal reason capture",task:"On closed-lost, prompt the rep for the reason and log it",workArea:"Sales / SDR",buildOrder:7,categories:["crm"],labels:["Automation"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM write",notes:"Capture pattern; builds win-loss data over time"},
  {id:"meeting-confirm-and-no-show-follow-up",title:"Meeting confirm and no-show follow-up",task:"Confirm meetings; reschedule on a no-show",workArea:"Sales / SDR",buildOrder:8,categories:["calendar","email","accounting"],labels:["Nudge"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Services",connectionSummary:"Calendar + email",notes:"Big for appointment-based businesses"},
  {id:"pre-call-brief",title:"Pre-call brief",task:"Assemble account context into Slack before the meeting",workArea:"Sales / SDR",buildOrder:9,categories:["crm","notify","calendar","accounting"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Calendar + CRM to Slack",notes:"Documented 2026 pattern"},
  {id:"proposal-doc-generation",title:"Proposal / doc generation",task:"Pull a deal record and generate a draft proposal or SOW",workArea:"Sales / SDR",buildOrder:10,categories:["crm","docs"],labels:["Draft"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"SaaS, Services",connectionSummary:"CRM read + doc tool",notes:"Draft-only and client-facing, so review is mandatory"},
  {id:"ticket-triage-and-tagging",title:"Ticket triage and tagging",task:"Classify and route inbound tickets",workArea:"Customer Success / Support",buildOrder:1,categories:["helpdesk","email"],labels:["Routing"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Helpdesk inbox",notes:"Canonical first agent; the 40-plus-hours-a-month win"},
  {id:"escalation-alert",title:"Escalation alert",task:"Ticket breaches SLA or is flagged high-priority; alert the owner",workArea:"Customer Success / Support",buildOrder:2,categories:["notify","helpdesk"],labels:["Flag"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Helpdesk read (Slack notify)",notes:"Notify-only"},
  {id:"customer-onboarding-kickoff",title:"Customer onboarding kickoff",task:"Closed-won fires the onboarding checklist, welcome, and first tasks",workArea:"Customer Success / Support",buildOrder:3,categories:["crm","notify","docs","hris","tasks-inbox"],labels:["Automation"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM trigger + tasks/Slack",notes:"Core to the framework you are building"},
  {id:"post-call-summary-to-task",title:"Post-call summary to task",task:"Turn a call into a summary written as a CRM task",workArea:"Customer Success / Support",buildOrder:4,categories:["crm","recorder"],labels:["Summary"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Recorder to CRM task",notes:"Live V1 flow. Strategic anchor for the in-flight account"},
  {id:"churn-risk-flag",title:"Churn-risk flag",task:"Watch usage signals and alert the owner",workArea:"Customer Success / Support",buildOrder:5,categories:["notify","analytics"],labels:["Flag"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"SaaS, Services",connectionSummary:"Product analytics to Slack",notes:"Resistance is mostly clean usage data"},
  {id:"expansion-upsell-signal",title:"Expansion / upsell signal",task:"Positive usage signals flag an upsell opportunity to the owner",workArea:"Customer Success / Support",buildOrder:6,categories:["notify","analytics"],labels:["Flag","New idea"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"SaaS, Services",connectionSummary:"Product analytics to Slack",notes:"NEW. Positive mirror of the churn flag; acts on growth, not risk"},
  {id:"csat-nps-follow-up-router",title:"CSAT / NPS follow-up router",task:"A low score triggers an owner alert and follow-up",workArea:"Customer Success / Support",buildOrder:7,categories:["notify","survey"],labels:["Notify"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Survey tool to Slack"},
  {id:"knowledge-base-gap-flag",title:"Knowledge-base gap flag",task:"Repeated unanswered questions flagged to create an article",workArea:"Customer Success / Support",buildOrder:8,categories:["helpdesk"],labels:["Q&A"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS, Services",connectionSummary:"Helpdesk read"},
  {id:"renewal-date-reminder",title:"Renewal-date reminder",task:"Nudge the owner ahead of the renewal window",workArea:"Customer Success / Support",buildOrder:9,categories:["crm","notify"],labels:["Nudge"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS, Services",connectionSummary:"CRM to Slack",notes:"Subscription / contract renewals"},
  {id:"first-response-draft",title:"First-response draft",task:"Draft the first reply to an inbound support message",workArea:"Customer Success / Support",buildOrder:10,categories:["helpdesk","email"],labels:["Draft"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Helpdesk inbox to draft",notes:"Draft-only"},
  {id:"content-repurposing",title:"Content repurposing",task:"Turn one long asset into channel-specific drafts",workArea:"Marketing",buildOrder:1,categories:[],labels:["Draft"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Minimal (optional CMS)",notes:"Number-one SMB entry point"},
  {id:"review-reputation-monitor",title:"Review / reputation monitor",task:"New Google or app-store review lands; negatives flagged fast",workArea:"Marketing",buildOrder:2,categories:["notify"],labels:["Flag"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"CPG, Services",connectionSummary:"Review source to Slack",notes:"Notify-only; First Wave for local, CPG, and services buyers"},
  {id:"inbound-lead-scoring-and-routing",title:"Inbound lead scoring and routing",task:"Score form fills and route to the right rep",workArea:"Marketing",buildOrder:3,categories:["crm","forms"],labels:["Routing"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Form to CRM",notes:"Touches live lead flow"},
  {id:"competitor-monitoring-digest",title:"Competitor-monitoring digest",task:"Scheduled summary of competitor moves to Slack",workArea:"Marketing",buildOrder:4,categories:["notify","web"],labels:["Summary"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Web to Slack (read-only)"},
  {id:"campaign-performance-summary",title:"Campaign performance summary",task:"Weekly performance rollup to Slack",workArea:"Marketing",buildOrder:5,categories:["notify","analytics"],labels:["Digest"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Analytics read to Slack"},
  {id:"seo-content-brief-generator",title:"SEO content brief generator",task:"Generate a content brief from a target keyword",workArea:"Marketing",buildOrder:6,categories:["seo"],labels:["Digest"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Search/SEO read"},
  {id:"campaign-utm-attribution-hygiene",title:"Campaign UTM / attribution hygiene",task:"Flag campaigns missing UTM or attribution",workArea:"Marketing",buildOrder:7,categories:["crm","analytics"],labels:["Flag"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Analytics/CRM read",notes:"Hygiene pattern for marketing data"},
  {id:"inbound-form-spam-filter",title:"Inbound form spam filter",task:"Flag or route junk form fills before they hit the CRM",workArea:"Marketing",buildOrder:8,categories:["crm","forms"],labels:["Routing"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Form to CRM"},
  {id:"ad-spend-pacing-alert",title:"Ad-spend pacing alert",task:"Alert when ad spend is pacing over or under plan",workArea:"Marketing",buildOrder:9,categories:["notify","accounting","ads"],labels:["Notify","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Ad platform read to Slack",notes:"NEW. Read + notify"},
  {id:"event-webinar-follow-up",title:"Event / webinar follow-up",task:"Post-event, route attendees to reps with context",workArea:"Marketing",buildOrder:10,categories:["crm","notify"],labels:["Routing"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Event tool to CRM/Slack"},
  {id:"dedup-and-data-hygiene-flagger",title:"Dedup and data-hygiene flagger",task:"Surface duplicates and anomalies into a tasks inbox",workArea:"RevOps / Operations",buildOrder:1,categories:["crm","email","tasks-inbox"],labels:["Reconcile"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read",notes:"Attio prototype generalized. Foundation play and flagship demo"},
  {id:"data-sync-watchdog",title:"Data-sync watchdog",task:"Alert when a sync between systems fails or stalls",workArea:"RevOps / Operations",buildOrder:2,categories:["warehouse","notify"],labels:["Notify"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Sync status read (Slack notify)",notes:"On-brand with the uncoordinated-sync problem"},
  {id:"meeting-notes-to-crm-record",title:"Meeting notes to CRM record",task:"Write meeting notes into the CRM record",workArea:"RevOps / Operations",buildOrder:3,categories:["crm","recorder"],labels:["Automation"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Recorder to CRM",notes:"Avoma-to-Attio pattern"},
  {id:"cross-system-reconciliation-flag",title:"Cross-system reconciliation flag",task:"Compare two systems and write mismatches to a tasks inbox",workArea:"RevOps / Operations",buildOrder:4,categories:["crm","enrichment","tasks-inbox"],labels:["Reconcile"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Two reads (read-only)",notes:"Attio-Amplemarket pattern"},
  {id:"ask-your-data-to-slack",title:"Ask-your-data to Slack",task:"Answer natural-language questions without dashboards or SQL",workArea:"RevOps / Operations",buildOrder:5,categories:["warehouse","notify"],labels:["Q&A"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Warehouse read to Slack",notes:"A compounding agent"},
  {id:"sales-to-cs-handoff",title:"Sales-to-CS handoff",task:"Closed-won packages deal context, creates the CS record, notifies the CSM",workArea:"RevOps / Operations",buildOrder:6,categories:["crm","notify"],labels:["Notify"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM trigger + record + Slack",notes:"The dropped-baton problem"},
  {id:"territory-assignment-hygiene",title:"Territory / assignment hygiene",task:"Flag unassigned or misrouted accounts",workArea:"RevOps / Operations",buildOrder:7,categories:["crm"],labels:["Routing"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read"},
  {id:"weekly-pipeline-change-digest",title:"Weekly pipeline change digest",task:"What moved in pipeline this week, to Slack",workArea:"RevOps / Operations",buildOrder:8,categories:["crm","notify"],labels:["Automation"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read to Slack"},
  {id:"stale-record-archival-flag",title:"Stale-record archival flag",task:"Flag records untouched in N months for archival",workArea:"RevOps / Operations",buildOrder:9,categories:["crm"],labels:["Flag","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read",notes:"NEW. Extends hygiene from 'is data missing' to 'should this still be here'"},
  {id:"lead-to-account-matching",title:"Lead-to-account matching",task:"Match inbound leads to existing accounts",workArea:"RevOps / Operations",buildOrder:10,categories:["crm"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"CRM read/write"},
  {id:"approval-routing-and-nudge",title:"Approval routing and nudge",task:"An over-threshold request routes to the approver; nudge if it stalls",workArea:"RevOps / Operations",buildOrder:11,categories:["crm","notify","forms"],labels:["Routing"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Form/CRM + Slack"},
  {id:"failed-payment-alert",title:"Failed-payment alert",task:"A Stripe event fires; ping the owner in Slack",workArea:"Finance / Accounting",buildOrder:1,categories:["notify","payments"],labels:["Notify"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Stripe webhook to Slack",notes:"Notify-only; revenue protection"},
  {id:"duplicate-invoice-double-payment-flag",title:"Duplicate-invoice / double-payment flag",task:"Flag duplicate vendor invoices before payment",workArea:"Finance / Accounting",buildOrder:2,categories:["notify","payments","accounting"],labels:["Reconcile"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Accounting read (Slack notify)",notes:"Cost protection. Sensitive read holds it at R2"},
  {id:"receipt-expense-capture",title:"Receipt / expense capture",task:"Forward or snap a receipt; get a categorized expense draft",workArea:"Finance / Accounting",buildOrder:3,categories:["email","accounting"],labels:["Draft"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Email/photo to expense draft",notes:"Capture pattern, near-zero resistance"},
  {id:"subscription-renewal-billing-reminder",title:"Subscription / renewal billing reminder",task:"Upcoming charges and renewals to the owner",workArea:"Finance / Accounting",buildOrder:4,categories:["notify","payments"],labels:["Automation"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS, Services",connectionSummary:"Billing read to Slack"},
  {id:"cash-position-low-balance-alert",title:"Cash-position / low-balance alert",task:"Balance below threshold; alert the owner",workArea:"Finance / Accounting",buildOrder:5,categories:["notify","accounting"],labels:["Notify"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Accounting read to Slack",notes:"Read-only"},
  {id:"vendor-renewal-auto-renew-alert",title:"Vendor renewal / auto-renew alert",task:"Alert ahead of vendor contract renewals and auto-renews",workArea:"Finance / Accounting",buildOrder:6,categories:["notify"],labels:["Notify","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Record read to Slack",notes:"NEW (procurement). Near-twin of Compliance/expiry monitor pointed at vendor contracts"},
  {id:"invoice-data-extraction",title:"Invoice data extraction",task:"Parse documents into the accounting system",workArea:"Finance / Accounting",buildOrder:7,categories:["docs","accounting"],labels:["Capture"],firstWave:false,impact:3,resistance:3,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Docs to accounting write",notes:"Highest write-risk. Build last with approval gating"},
  {id:"expense-flagging-and-auditing",title:"Expense flagging and auditing",task:"Surface expense anomalies for review",workArea:"Finance / Accounting",buildOrder:8,categories:["accounting"],labels:["Flag"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Accounting read",notes:"Read-only keeps it safe"},
  {id:"ar-follow-up-reminders",title:"AR follow-up reminders",task:"Draft chase emails on overdue invoices",workArea:"Finance / Accounting",buildOrder:9,categories:["email","accounting"],labels:["Draft"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Accounting to email draft",notes:"Draft-only"},
  {id:"spend-anomaly-budget-overrun-alert",title:"Spend-anomaly / budget-overrun alert",task:"A category goes over budget; alert",workArea:"Finance / Accounting",buildOrder:10,categories:["notify","accounting"],labels:["Notify"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Accounting read to Slack"},
  {id:"vendor-onboarding-doc-chase",title:"Vendor onboarding doc chase",task:"Chase missing vendor docs (W-9, banking)",workArea:"Finance / Accounting",buildOrder:11,categories:["email","docs"],labels:["Nudge"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Email + record"},
  {id:"purchase-requisition-intake-and-routing",title:"Purchase requisition intake and routing",task:"Structure purchase requests and route to the approver",workArea:"Finance / Accounting",buildOrder:12,categories:["notify","forms"],labels:["Routing","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Form + Slack",notes:"NEW (procurement)"},
  {id:"compliance-expiry-monitor",title:"Compliance / expiry monitor",task:"Licenses, certs, insurance, contract end-dates alert ahead of deadline",workArea:"Docs / Legal",buildOrder:1,categories:["notify"],labels:["Notify"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Services",connectionSummary:"Record read to Slack",notes:"Kin to the renewal reminder, different domain"},
  {id:"nda-standard-doc-generator",title:"NDA / standard-doc generator",task:"Generate a standard NDA or MSA from a template and parameters",workArea:"Docs / Legal",buildOrder:2,categories:["docs"],labels:["Generate"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Template + params"},
  {id:"signature-status-chaser",title:"Signature-status chaser",task:"An e-sign is pending past X days; nudge",workArea:"Docs / Legal",buildOrder:3,categories:["notify","esign"],labels:["Nudge"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"E-sign webhook + Slack"},
  {id:"contract-document-intake",title:"Contract / document intake",task:"A new file lands in storage; extract key terms and write them to a record",workArea:"Docs / Legal",buildOrder:4,categories:["crm","storage"],labels:["Capture"],firstWave:false,impact:2,resistance:3,score:-1,sizeFit:"Mid-market+",verticalFit:"SaaS, Services",connectionSummary:"Storage + webhook + CRM write",notes:"Generalized sibling of invoice extraction. Sensitive, later-wave"},
  {id:"contract-obligation-tracker",title:"Contract obligation tracker",task:"Extract key obligations and dates from signed contracts into a record",workArea:"Docs / Legal",buildOrder:5,categories:["docs"],labels:["Capture"],firstWave:false,impact:2,resistance:3,score:-1,sizeFit:"Mid-market+",verticalFit:"SaaS, Services",connectionSummary:"Docs to record",notes:"Sibling of intake, ongoing tracking"},
  {id:"security-questionnaire-draft",title:"Security-questionnaire draft",task:"Draft answers to inbound RFP and vendor-security questionnaires from a knowledge base",workArea:"Security / Trust & Compliance",buildOrder:1,categories:["docs"],labels:["Draft","New idea"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Knowledge base read to draft",notes:"NEW. A SaaS deal-cycle unlock; one of the most hated tasks. New First Wave"},
  {id:"pii-in-the-wrong-place-flag",title:"PII-in-the-wrong-place flag",task:"Scan records and files for PII in fields that should not hold it; flag",workArea:"Security / Trust & Compliance",buildOrder:2,categories:["crm","storage"],labels:["Flag","New idea"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"CRM/storage read",notes:"NEW. Risk reduction. Data governance"},
  {id:"access-review-recertification-reminder",title:"Access-review / recertification reminder",task:"Periodic reminder to managers to review who has access",workArea:"Security / Trust & Compliance",buildOrder:3,categories:["notify","hris","identity"],labels:["Nudge","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"IAM/HRIS read to Slack",notes:"NEW"},
  {id:"soc2-evidence-collection-nudge",title:"SOC2 / evidence-collection nudge",task:"Nudge owners to collect and upload audit evidence ahead of an audit",workArea:"Security / Trust & Compliance",buildOrder:4,categories:["notify","docs"],labels:["Nudge","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"SaaS",connectionSummary:"Checklist read to Slack",notes:"NEW"},
  {id:"phishing-report-triage",title:"Phishing-report triage",task:"User-reported phishing emails triaged and flagged to security",workArea:"Security / Trust & Compliance",buildOrder:5,categories:["notify","email","issues"],labels:["Triage","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Inbox/security read to Slack",notes:"NEW"},
  {id:"vendor-security-review-intake",title:"Vendor-security-review intake",task:"Structure inbound vendor security reviews into a record or checklist",workArea:"Security / Trust & Compliance",buildOrder:6,categories:["email","docs","forms"],labels:["Capture","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"SaaS, Services",connectionSummary:"Form/email to record",notes:"NEW"},
  {id:"stockout-low-stock-alert",title:"Stockout / low-stock alert",task:"Stock crosses reorder point; ping the owner in Slack",workArea:"Inventory / Supply",buildOrder:1,categories:["notify","ims"],labels:["Notify"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"CPG",connectionSummary:"IMS or sheet read to Slack",notes:"Twin of the Failed-payment alert"},
  {id:"stock-reconciliation-flag",title:"Stock reconciliation flag",task:"Compare two systems and write mismatches to a tasks inbox",workArea:"Inventory / Supply",buildOrder:2,categories:["ims","tasks-inbox"],labels:["Reconcile"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"CPG",connectionSummary:"Two reads (read-only)",notes:"Storefront vs IMS, 3PL vs IMS, IMS vs accounting"},
  {id:"reorder-draft-po",title:"Reorder draft-PO",task:"When stock is low, draft a purchase order or supplier email for approval",workArea:"Inventory / Supply",buildOrder:3,categories:["email","ims"],labels:["Draft"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"All",verticalFit:"CPG",connectionSummary:"IMS read to email/PO draft",notes:"Draft-only keeps the human in the loop"},
  {id:"dead-stock-flag",title:"Dead-stock flag",task:"Flag SKUs with no movement in N days",workArea:"Inventory / Supply",buildOrder:4,categories:["notify","ims"],labels:["Flag"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"CPG",connectionSummary:"IMS or sheet read to Slack",notes:"Frees working capital"},
  {id:"manual-stock-capture",title:"Manual stock capture",task:"Staff message 'received 40 of SKU-123'; structure it into a record",workArea:"Inventory / Supply",buildOrder:5,categories:["email","forms","ims"],labels:["Capture"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"CPG",connectionSummary:"Chat/email/form to record",notes:"For businesses with NO system. Creates the data layer as a byproduct"},
  {id:"shipment-delivery-tracking-alert",title:"Shipment / delivery tracking alert",task:"Flag late or stuck shipments",workArea:"Inventory / Supply",buildOrder:6,categories:["notify","ims"],labels:["Flag"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"CPG",connectionSummary:"Carrier/IMS read to Slack"},
  {id:"supplier-eta-backorder-monitor",title:"Supplier ETA / backorder monitor",task:"Parse supplier updates; flag delays",workArea:"Inventory / Supply",buildOrder:7,categories:["email","ims"],labels:["Capture"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"CPG",connectionSummary:"Email/IMS read"},
  {id:"price-change-cost-increase-monitor",title:"Price-change / cost-increase monitor",task:"A supplier cost change flags a margin impact",workArea:"Inventory / Supply",buildOrder:8,categories:["notify","email","ims"],labels:["Flag"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"CPG",connectionSummary:"IMS/email read to Slack"},
  {id:"returns-rma-intake",title:"Returns / RMA intake",task:"Structure return requests into a record",workArea:"Inventory / Supply",buildOrder:9,categories:["email","forms"],labels:["Capture"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"CPG",connectionSummary:"Form/email to record"},
  {id:"demand-spike-alert",title:"Demand spike alert",task:"Unusual order velocity on a SKU; alert",workArea:"Inventory / Supply",buildOrder:10,categories:["notify","ims"],labels:["Notify"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"CPG",connectionSummary:"Orders read to Slack"},
  {id:"project-budget-burn-alert",title:"Project budget-burn alert",task:"Alert when a project crosses a budget or hours threshold",workArea:"Professional Services",buildOrder:1,categories:["notify","accounting","psa"],labels:["Notify","New idea"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Services",connectionSummary:"PSA read to Slack",notes:"NEW. Notify-only; margin protection. New First Wave"},
  {id:"timesheet-chaser",title:"Timesheet chaser",task:"Chase missing timesheets",workArea:"Professional Services",buildOrder:2,categories:["notify","psa"],labels:["Nudge","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Services",connectionSummary:"PSA/time tool read to Slack",notes:"NEW. The classic services pain"},
  {id:"client-status-update-draft",title:"Client status-update draft",task:"Draft a weekly client status update from project data",workArea:"Professional Services",buildOrder:3,categories:["docs","psa"],labels:["Draft","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Services",connectionSummary:"PSA/PM read to draft",notes:"NEW"},
  {id:"work-order-job-intake",title:"Work-order / job intake",task:"Structure inbound job and work-order requests into a record",workArea:"Professional Services",buildOrder:4,categories:["email","forms","psa"],labels:["Capture","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Services",connectionSummary:"Form/email to record",notes:"NEW"},
  {id:"change-order-tracking",title:"Change-order tracking",task:"Flag scope changes and track change orders",workArea:"Professional Services",buildOrder:5,categories:["email","ims","psa"],labels:["Flag","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Services",connectionSummary:"PSA/email read to flag",notes:"NEW"},
  {id:"mdf-co-marketing-request-routing",title:"MDF / co-marketing request routing",task:"Route MDF and co-marketing requests to the approver",workArea:"Partnerships / Channel",buildOrder:1,categories:["notify","forms"],labels:["Routing","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Form + Slack",notes:"NEW"},
  {id:"partner-deal-registration-intake",title:"Partner deal-registration intake",task:"Structure partner deal-registration submissions into the CRM",workArea:"Partnerships / Channel",buildOrder:2,categories:["crm","forms"],labels:["Capture","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Form to CRM",notes:"NEW"},
  {id:"partner-onboarding-kickoff",title:"Partner onboarding kickoff",task:"A new partner triggers an onboarding checklist",workArea:"Partnerships / Channel",buildOrder:3,categories:["crm","notify","docs","hris","tasks-inbox"],labels:["Automation","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"CRM trigger + tasks/Slack",notes:"NEW"},
  {id:"new-hire-onboarding-notifier",title:"New-hire onboarding notifier",task:"Run a checklist and send Slack pings on new hires",workArea:"HR / People",buildOrder:1,categories:["notify","docs","hris"],labels:["Notify"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"HRIS to Slack (notify-only)"},
  {id:"pto-time-off-request-router",title:"PTO / time-off request router",task:"Route time-off requests and notify the manager",workArea:"HR / People",buildOrder:2,categories:["notify","forms","hris"],labels:["Routing"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"HRIS/form to Slack"},
  {id:"onboarding-doc-chaser",title:"Onboarding-doc chaser",task:"Chase missing new-hire paperwork",workArea:"HR / People",buildOrder:3,categories:["email","hris"],labels:["Nudge"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Email + record"},
  {id:"hr-policy-q-a",title:"HR policy Q&A",task:"Answer benefits, PTO, and policy questions over docs",workArea:"HR / People",buildOrder:4,categories:["docs","hris"],labels:["Q&A"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Docs read",notes:"Same pattern as IT knowledge Q&A, HR domain"},
  {id:"candidate-status-nudge",title:"Candidate-status nudge",task:"Stale candidates in the pipeline nudge the recruiter",workArea:"HR / People",buildOrder:5,categories:["notify","ats"],labels:["Nudge"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"ATS read to Slack"},
  {id:"interview-feedback-chaser",title:"Interview-feedback chaser",task:"Chase interviewers for their scorecards",workArea:"HR / People",buildOrder:6,categories:["notify","ats"],labels:["Nudge","New idea"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"ATS read to Slack",notes:"NEW. A real, specific recruiting pain"},
  {id:"resume-summary",title:"Resume summary",task:"Summarize candidates for reviewers",workArea:"HR / People",buildOrder:7,categories:["ats"],labels:["Summary"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"ATS read",notes:"Keep assistive and human-decided; bias and PII risk"},
  {id:"interview-scheduling",title:"Interview scheduling",task:"Coordinate interview slots",workArea:"HR / People",buildOrder:8,categories:["calendar","accounting","ats"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Calendar"},
  {id:"offer-letter-doc-generator",title:"Offer-letter / doc generator",task:"Generate offer and onboarding docs from a template",workArea:"HR / People",buildOrder:9,categories:["docs","hris"],labels:["Generate"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Template + HRIS"},
  {id:"offboarding-checklist-trigger",title:"Offboarding checklist trigger",task:"A departure triggers access-removal and checklist tasks",workArea:"HR / People",buildOrder:10,categories:["docs","hris","identity"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"HRIS trigger + tasks",notes:"Coordinate with IT deprovisioning"},
  {id:"celebration-notifier",title:"Celebration notifier",task:"Birthday, anniversary, and milestone pings",workArea:"HR / People",buildOrder:11,categories:["notify","hris"],labels:["Notify"],firstWave:false,impact:1,resistance:1,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"HRIS read to Slack",notes:"Low impact, culture nicety"},
  {id:"outage-incident-alert-router",title:"Outage / incident alert router",task:"A monitoring alert routes to the right on-call in Slack",workArea:"IT / Internal",buildOrder:1,categories:["notify","recorder","monitoring"],labels:["Routing"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Monitoring read to Slack",notes:"Notify-only"},
  {id:"access-request-triage",title:"Access-request triage",task:"Route and pre-fill access requests",workArea:"IT / Internal",buildOrder:2,categories:["identity","itsm"],labels:["Routing"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"ITSM",notes:"Human-in-the-loop on escalation holds it at R2"},
  {id:"new-hire-provisioning-checklist",title:"New-hire provisioning checklist",task:"Trigger account and tool provisioning tasks on hire",workArea:"IT / Internal",buildOrder:3,categories:["hris","identity","itsm"],labels:["Automation"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"HRIS trigger + ITSM tasks",notes:"Pairs with HR onboarding"},
  {id:"offboarding-deprovisioning-flag",title:"Offboarding deprovisioning flag",task:"A departure flags access to revoke",workArea:"IT / Internal",buildOrder:4,categories:["hris","identity","itsm"],labels:["Flag"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"HRIS trigger + ITSM",notes:"Flag-only keeps it at R2; security value"},
  {id:"permission-access-drift-flag",title:"Permission / access-drift flag",task:"Flag users whose access exceeds their role or peers",workArea:"IT / Internal",buildOrder:5,categories:["identity"],labels:["Flag","New idea"],firstWave:false,impact:3,resistance:2,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"IAM/SSO read",notes:"NEW. Data/access governance; risk reduction"},
  {id:"internal-knowledge-q-a",title:"Internal knowledge Q&A",task:"Answer policy and how-to questions over your docs",workArea:"IT / Internal",buildOrder:6,categories:["docs"],labels:["Q&A"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Docs read",notes:"Classic deflection win"},
  {id:"password-reset-common-request-deflector",title:"Password-reset / common-request deflector",task:"Handle routine self-service requests",workArea:"IT / Internal",buildOrder:7,categories:["itsm"],labels:["Routing"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"ITSM read/action",notes:"The textbook first IT agent"},
  {id:"saas-license-seat-audit",title:"SaaS license / seat audit",task:"Flag unused seats for cost savings",workArea:"IT / Internal",buildOrder:8,categories:["identity"],labels:["Flag"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"SaaS admin read",notes:"Read-only"},
  {id:"shadow-it-new-app-flag",title:"Shadow-IT / new-app flag",task:"Flag new SaaS signups on the company domain",workArea:"IT / Internal",buildOrder:9,categories:["email","identity"],labels:["Flag"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"Universal",connectionSummary:"Email/SSO read"},
  {id:"meeting-summary-and-action-items",title:"Meeting summary and action items",task:"Summarize meetings and route action items to owners",workArea:"Executive / Admin",buildOrder:1,categories:["notify","recorder"],labels:["Summary"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Recorder to Slack",notes:"Travels across every department; strong demo piece"},
  {id:"daily-priority-brief",title:"Daily priority brief",task:"A morning brief of calendar, tasks, and flags to Slack",workArea:"Executive / Admin",buildOrder:2,categories:["notify","calendar"],labels:["Digest"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Calendar/tasks read to Slack"},
  {id:"email-follow-up-reminder",title:"Email follow-up reminder",task:"No reply in X days; remind the sender",workArea:"Executive / Admin",buildOrder:3,categories:["notify","email"],labels:["Nudge"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Inbox read to Slack"},
  {id:"recurring-report-draft",title:"Recurring report draft",task:"Draft a recurring report skeleton from its sources",workArea:"Executive / Admin",buildOrder:4,categories:["docs","issues"],labels:["Draft"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Multiple reads to doc"},
  {id:"board-investor-update-draft",title:"Board / investor-update draft",task:"Draft a board or investor update from metrics",workArea:"Executive / Admin",buildOrder:5,categories:["docs"],labels:["Draft","New idea"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Multiple reads to doc",notes:"NEW. For startup buyers"},
  {id:"inbox-triage-and-priority-flag",title:"Inbox triage and priority flag",task:"Label and surface what matters in the inbox",workArea:"Executive / Admin",buildOrder:6,categories:["email"],labels:["Flag"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Inbox read"},
  {id:"weekly-digest-assembler",title:"Weekly digest assembler",task:"Roll multiple sources into one Slack post",workArea:"Executive / Admin",buildOrder:7,categories:["notify"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Several reads to Slack"},
  {id:"action-item-commitment-tracker",title:"Action-item / commitment tracker",task:"Track action items to completion across meetings",workArea:"Executive / Admin",buildOrder:8,categories:["notify","recorder"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Recorder/tasks read + Slack"},
  {id:"travel-expense-itinerary-assembler",title:"Travel / expense itinerary assembler",task:"Compile trip details into one view",workArea:"Executive / Admin",buildOrder:9,categories:["calendar","email","accounting"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"Universal",connectionSummary:"Email/calendar read"},
  {id:"error-incident-spike-alert",title:"Error / incident spike alert",task:"An error spike routes to the team in Slack",workArea:"Product / Engineering",buildOrder:1,categories:["notify","monitoring"],labels:["Routing"],firstWave:true,impact:3,resistance:1,score:2,sizeFit:"Mid-market+",verticalFit:"SaaS",connectionSummary:"Observability read to Slack",notes:"Notify-only. Near-twin of IT outage router, product domain"},
  {id:"release-notes-draft",title:"Release-notes draft",task:"Draft release notes from merged changes",workArea:"Product / Engineering",buildOrder:2,categories:["docs","issues"],labels:["Draft"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Repo/issue read to doc"},
  {id:"feature-request-capture",title:"Feature-request capture",task:"Structure feature requests from support and sales into a board",workArea:"Product / Engineering",buildOrder:3,categories:["crm","helpdesk","docs","issues"],labels:["Capture"],firstWave:false,impact:2,resistance:1,score:1,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Helpdesk/CRM to PM tool"},
  {id:"bug-report-triage",title:"Bug-report triage",task:"Classify and route inbound bug reports",workArea:"Product / Engineering",buildOrder:4,categories:["issues"],labels:["Routing"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"All",verticalFit:"SaaS",connectionSummary:"Issue tracker read/write"},
  {id:"customer-feedback-aggregator",title:"Customer-feedback aggregator",task:"Cluster feedback from tickets and calls into themes",workArea:"Product / Engineering",buildOrder:5,categories:["helpdesk","recorder"],labels:["Automation"],firstWave:false,impact:2,resistance:2,score:0,sizeFit:"Mid-market+",verticalFit:"SaaS",connectionSummary:"Helpdesk/recorder read"},
];

export function getLibraryAgent(id: string): LibraryAgent | undefined {
  return AGENT_LIBRARY.find((a) => a.id === id);
}

/** Distinct work areas in catalog order (for the browse facet). */
export const WORK_AREAS: string[] = [
  ...new Set(AGENT_LIBRARY.map((a) => a.workArea)),
];

/** Distinct labels across the catalog (for the browse facet). */
export const LIBRARY_LABELS: string[] = [
  ...new Set(AGENT_LIBRARY.flatMap((a) => a.labels)),
].sort();
