// AUTO-GENERATED from anthropics/knowledge-work-plugins (Apache-2.0).
// A browsable catalog of that repo's Agent Skills — installable into a
// workspace via the existing GitHub skill-install path (ref = owner/repo/path).
// 95 skills. Regenerate when the upstream repo changes.

export type KnowledgeWorkSkill = {
  /** Source plugin / work area, e.g. "sales". */
  domain: string;
  /** Skill folder name, e.g. "call-prep". */
  name: string;
  /** One-line description from the skill's SKILL.md frontmatter. */
  description: string;
  /** owner/repo/path ref for installFromGitHubAction. */
  ref: string;
};

export const KNOWLEDGE_WORK_SKILLS: KnowledgeWorkSkill[] = [
  {domain:"sales",name:"account-research",description:"Research a company or person and get actionable sales intel.",ref:"anthropics/knowledge-work-plugins/sales/skills/account-research"},
  {domain:"sales",name:"call-prep",description:"Prepare for a sales call with account context, attendee research, and suggested agenda.",ref:"anthropics/knowledge-work-plugins/sales/skills/call-prep"},
  {domain:"sales",name:"call-summary",description:"Process call notes or a transcript — extract action items, draft follow-up email, generate internal summary.",ref:"anthropics/knowledge-work-plugins/sales/skills/call-summary"},
  {domain:"sales",name:"competitive-intelligence",description:"Research your competitors and build an interactive battlecard. Outputs an HTML artifact with clickable competitor cards and a comparison matrix.",ref:"anthropics/knowledge-work-plugins/sales/skills/competitive-intelligence"},
  {domain:"sales",name:"create-an-asset",description:"Generate tailored sales assets (landing pages, decks, one-pagers, workflow demos) from your deal context. Describe your prospect, audience, and goal — get a polished, branded asset ready to share with customers.",ref:"anthropics/knowledge-work-plugins/sales/skills/create-an-asset"},
  {domain:"sales",name:"daily-briefing",description:"Start your day with a prioritized sales briefing.",ref:"anthropics/knowledge-work-plugins/sales/skills/daily-briefing"},
  {domain:"sales",name:"draft-outreach",description:"Research a prospect then draft personalized outreach. Uses web research by default, supercharged with enrichment and CRM.",ref:"anthropics/knowledge-work-plugins/sales/skills/draft-outreach"},
  {domain:"sales",name:"forecast",description:"Generate a weighted sales forecast with best/likely/worst scenarios, commit vs. upside breakdown, and gap analysis.",ref:"anthropics/knowledge-work-plugins/sales/skills/forecast"},
  {domain:"sales",name:"pipeline-review",description:"Analyze pipeline health — prioritize deals, flag risks, get a weekly action plan.",ref:"anthropics/knowledge-work-plugins/sales/skills/pipeline-review"},
  {domain:"customer-support",name:"customer-escalation",description:"Package an escalation for engineering, product, or leadership with full context.",ref:"anthropics/knowledge-work-plugins/customer-support/skills/customer-escalation"},
  {domain:"customer-support",name:"customer-research",description:"Multi-source research on a customer question or topic with source attribution.",ref:"anthropics/knowledge-work-plugins/customer-support/skills/customer-research"},
  {domain:"customer-support",name:"draft-response",description:"Draft a professional customer-facing response tailored to the situation and relationship.",ref:"anthropics/knowledge-work-plugins/customer-support/skills/draft-response"},
  {domain:"customer-support",name:"kb-article",description:"Draft a knowledge base article from a resolved issue or common question.",ref:"anthropics/knowledge-work-plugins/customer-support/skills/kb-article"},
  {domain:"customer-support",name:"ticket-triage",description:"Triage and prioritize a support ticket or customer issue.",ref:"anthropics/knowledge-work-plugins/customer-support/skills/ticket-triage"},
  {domain:"marketing",name:"brand-review",description:"Review content against your brand voice, style guide, and messaging pillars, flagging deviations by severity with specific before/after fixes.",ref:"anthropics/knowledge-work-plugins/marketing/skills/brand-review"},
  {domain:"marketing",name:"campaign-plan",description:"Generate a full campaign brief with objectives, audience, messaging, channel strategy, content calendar, and success metrics.",ref:"anthropics/knowledge-work-plugins/marketing/skills/campaign-plan"},
  {domain:"marketing",name:"competitive-brief",description:"Research competitors and generate a positioning and messaging comparison with content gaps, opportunities, and threats.",ref:"anthropics/knowledge-work-plugins/marketing/skills/competitive-brief"},
  {domain:"marketing",name:"content-creation",description:"Draft marketing content across channels — blog posts, social media, email newsletters, landing pages, press releases, and case studies.",ref:"anthropics/knowledge-work-plugins/marketing/skills/content-creation"},
  {domain:"marketing",name:"draft-content",description:"Draft blog posts, social media, email newsletters, landing pages, press releases, and case studies with channel-specific formatting and SEO recommendations.",ref:"anthropics/knowledge-work-plugins/marketing/skills/draft-content"},
  {domain:"marketing",name:"email-sequence",description:"Design and draft multi-email sequences with full copy, timing, branching logic, exit conditions, and performance benchmarks.",ref:"anthropics/knowledge-work-plugins/marketing/skills/email-sequence"},
  {domain:"marketing",name:"performance-report",description:"Build a marketing performance report with key metrics, trend analysis, wins and misses, and prioritized optimization recommendations.",ref:"anthropics/knowledge-work-plugins/marketing/skills/performance-report"},
  {domain:"marketing",name:"seo-audit",description:"Run a comprehensive SEO audit — keyword research, on-page analysis, content gaps, technical checks, and competitor comparison.",ref:"anthropics/knowledge-work-plugins/marketing/skills/seo-audit"},
  {domain:"finance",name:"audit-support",description:"Support SOX 404 compliance with control testing methodology, sample selection, and documentation standards.",ref:"anthropics/knowledge-work-plugins/finance/skills/audit-support"},
  {domain:"finance",name:"close-management",description:"Manage the month-end close process with task sequencing, dependencies, and status tracking.",ref:"anthropics/knowledge-work-plugins/finance/skills/close-management"},
  {domain:"finance",name:"financial-statements",description:"Generate financial statements (income statement, balance sheet, cash flow) with period-over-period comparison and variance analysis.",ref:"anthropics/knowledge-work-plugins/finance/skills/financial-statements"},
  {domain:"finance",name:"journal-entry-prep",description:"Prepare journal entries with proper debits, credits, and supporting documentation for month-end close.",ref:"anthropics/knowledge-work-plugins/finance/skills/journal-entry-prep"},
  {domain:"finance",name:"journal-entry",description:"Prepare journal entries with proper debits, credits, and supporting detail.",ref:"anthropics/knowledge-work-plugins/finance/skills/journal-entry"},
  {domain:"finance",name:"reconciliation",description:"Reconcile accounts by comparing GL balances to subledgers, bank statements, or third-party data.",ref:"anthropics/knowledge-work-plugins/finance/skills/reconciliation"},
  {domain:"finance",name:"sox-testing",description:"Generate SOX sample selections, testing workpapers, and control assessments.",ref:"anthropics/knowledge-work-plugins/finance/skills/sox-testing"},
  {domain:"finance",name:"variance-analysis",description:"Decompose financial variances into drivers with narrative explanations and waterfall analysis.",ref:"anthropics/knowledge-work-plugins/finance/skills/variance-analysis"},
  {domain:"legal",name:"brief",description:"Generate contextual briefings for legal work — daily summary, topic research, or incident response.",ref:"anthropics/knowledge-work-plugins/legal/skills/brief"},
  {domain:"legal",name:"compliance-check",description:"Run a compliance check on a proposed action, product feature, or business initiative, surfacing applicable regulations, required approvals, and risk areas.",ref:"anthropics/knowledge-work-plugins/legal/skills/compliance-check"},
  {domain:"legal",name:"legal-response",description:"Generate a response to a common legal inquiry using configured templates, with built-in escalation checks for situations that shouldn't use a templated reply.",ref:"anthropics/knowledge-work-plugins/legal/skills/legal-response"},
  {domain:"legal",name:"legal-risk-assessment",description:"Assess and classify legal risks using a severity-by-likelihood framework with escalation criteria.",ref:"anthropics/knowledge-work-plugins/legal/skills/legal-risk-assessment"},
  {domain:"legal",name:"meeting-briefing",description:"Prepare structured briefings for meetings with legal relevance and track resulting action items.",ref:"anthropics/knowledge-work-plugins/legal/skills/meeting-briefing"},
  {domain:"legal",name:"review-contract",description:"Review a contract against your organization's negotiation playbook — flag deviations, generate redlines, provide business impact analysis.",ref:"anthropics/knowledge-work-plugins/legal/skills/review-contract"},
  {domain:"legal",name:"signature-request",description:"Prepare and route a document for e-signature — run a pre-signature checklist, configure signing order, and send for execution.",ref:"anthropics/knowledge-work-plugins/legal/skills/signature-request"},
  {domain:"legal",name:"triage-nda",description:"Rapidly triage an incoming NDA and classify it as GREEN (standard approval), YELLOW (counsel review), or RED (full legal review).",ref:"anthropics/knowledge-work-plugins/legal/skills/triage-nda"},
  {domain:"legal",name:"vendor-check",description:"Check the status of existing agreements with a vendor across all connected systems — CLM, CRM, email, and document storage — with gap analysis and upcoming deadlines.",ref:"anthropics/knowledge-work-plugins/legal/skills/vendor-check"},
  {domain:"operations",name:"capacity-plan",description:"Plan resource capacity — workload analysis and utilization forecasting.",ref:"anthropics/knowledge-work-plugins/operations/skills/capacity-plan"},
  {domain:"operations",name:"change-request",description:"Create a change management request with impact analysis and rollback plan.",ref:"anthropics/knowledge-work-plugins/operations/skills/change-request"},
  {domain:"operations",name:"compliance-tracking",description:"Track compliance requirements and audit readiness.",ref:"anthropics/knowledge-work-plugins/operations/skills/compliance-tracking"},
  {domain:"operations",name:"process-doc",description:"Document a business process — flowcharts, RACI, and SOPs.",ref:"anthropics/knowledge-work-plugins/operations/skills/process-doc"},
  {domain:"operations",name:"process-optimization",description:"Analyze and improve business processes.",ref:"anthropics/knowledge-work-plugins/operations/skills/process-optimization"},
  {domain:"operations",name:"risk-assessment",description:"Identify, assess, and mitigate operational risks.",ref:"anthropics/knowledge-work-plugins/operations/skills/risk-assessment"},
  {domain:"operations",name:"runbook",description:"Create or update an operational runbook for a recurring task or procedure.",ref:"anthropics/knowledge-work-plugins/operations/skills/runbook"},
  {domain:"operations",name:"status-report",description:"Generate a status report with KPIs, risks, and action items.",ref:"anthropics/knowledge-work-plugins/operations/skills/status-report"},
  {domain:"operations",name:"vendor-review",description:"Evaluate a vendor — cost analysis, risk assessment, and recommendation.",ref:"anthropics/knowledge-work-plugins/operations/skills/vendor-review"},
  {domain:"human-resources",name:"comp-analysis",description:"Analyze compensation — benchmarking, band placement, and equity modeling.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/comp-analysis"},
  {domain:"human-resources",name:"draft-offer",description:"Draft an offer letter with comp details and terms.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/draft-offer"},
  {domain:"human-resources",name:"interview-prep",description:"Create structured interview plans with competency-based questions and scorecards.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/interview-prep"},
  {domain:"human-resources",name:"onboarding",description:"Generate an onboarding checklist and first-week plan for a new hire.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/onboarding"},
  {domain:"human-resources",name:"org-planning",description:"Headcount planning, org design, and team structure optimization.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/org-planning"},
  {domain:"human-resources",name:"people-report",description:"Generate headcount, attrition, diversity, or org health reports.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/people-report"},
  {domain:"human-resources",name:"performance-review",description:"Structure a performance review with self-assessment, manager template, and calibration prep.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/performance-review"},
  {domain:"human-resources",name:"policy-lookup",description:"Find and explain company policies in plain language.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/policy-lookup"},
  {domain:"human-resources",name:"recruiting-pipeline",description:"Track and manage recruiting pipeline stages.",ref:"anthropics/knowledge-work-plugins/human-resources/skills/recruiting-pipeline"},
  {domain:"product-management",name:"competitive-brief",description:"Create a competitive analysis brief for one or more competitors or a feature area.",ref:"anthropics/knowledge-work-plugins/product-management/skills/competitive-brief"},
  {domain:"product-management",name:"metrics-review",description:"Review and analyze product metrics with trend analysis and actionable insights.",ref:"anthropics/knowledge-work-plugins/product-management/skills/metrics-review"},
  {domain:"product-management",name:"product-brainstorming",description:"Brainstorm product ideas, explore problem spaces, and challenge assumptions as a thinking partner.",ref:"anthropics/knowledge-work-plugins/product-management/skills/product-brainstorming"},
  {domain:"product-management",name:"roadmap-update",description:"Update, create, or reprioritize your product roadmap.",ref:"anthropics/knowledge-work-plugins/product-management/skills/roadmap-update"},
  {domain:"product-management",name:"sprint-planning",description:"Plan a sprint — scope work, estimate capacity, set goals, and draft a sprint plan.",ref:"anthropics/knowledge-work-plugins/product-management/skills/sprint-planning"},
  {domain:"product-management",name:"stakeholder-update",description:"Generate a stakeholder update tailored to audience and cadence.",ref:"anthropics/knowledge-work-plugins/product-management/skills/stakeholder-update"},
  {domain:"product-management",name:"synthesize-research",description:"Synthesize user research from interviews, surveys, and feedback into structured insights.",ref:"anthropics/knowledge-work-plugins/product-management/skills/synthesize-research"},
  {domain:"product-management",name:"write-spec",description:"Write a feature spec or PRD from a problem statement or feature idea.",ref:"anthropics/knowledge-work-plugins/product-management/skills/write-spec"},
  {domain:"data",name:"analyze",description:"Answer data questions -- from quick lookups to full analyses.",ref:"anthropics/knowledge-work-plugins/data/skills/analyze"},
  {domain:"data",name:"build-dashboard",description:"Build an interactive HTML dashboard with charts, filters, and tables.",ref:"anthropics/knowledge-work-plugins/data/skills/build-dashboard"},
  {domain:"data",name:"create-viz",description:"Create publication-quality visualizations with Python.",ref:"anthropics/knowledge-work-plugins/data/skills/create-viz"},
  {domain:"data",name:"data-context-extractor",description:">",ref:"anthropics/knowledge-work-plugins/data/skills/data-context-extractor"},
  {domain:"data",name:"data-visualization",description:"Create effective data visualizations with Python (matplotlib, seaborn, plotly).",ref:"anthropics/knowledge-work-plugins/data/skills/data-visualization"},
  {domain:"data",name:"explore-data",description:"Profile and explore a dataset to understand its shape, quality, and patterns.",ref:"anthropics/knowledge-work-plugins/data/skills/explore-data"},
  {domain:"data",name:"sql-queries",description:"Write correct, performant SQL across all major data warehouse dialects (Snowflake, BigQuery, Databricks, PostgreSQL, etc.).",ref:"anthropics/knowledge-work-plugins/data/skills/sql-queries"},
  {domain:"data",name:"statistical-analysis",description:"Apply statistical methods including descriptive stats, trend analysis, outlier detection, and hypothesis testing.",ref:"anthropics/knowledge-work-plugins/data/skills/statistical-analysis"},
  {domain:"data",name:"validate-data",description:"QA an analysis before sharing -- methodology, accuracy, and bias checks.",ref:"anthropics/knowledge-work-plugins/data/skills/validate-data"},
  {domain:"data",name:"write-query",description:"Write optimized SQL for your dialect with best practices.",ref:"anthropics/knowledge-work-plugins/data/skills/write-query"},
  {domain:"engineering",name:"architecture",description:"Create or evaluate an architecture decision record (ADR).",ref:"anthropics/knowledge-work-plugins/engineering/skills/architecture"},
  {domain:"engineering",name:"code-review",description:"Review code changes for security, performance, and correctness.",ref:"anthropics/knowledge-work-plugins/engineering/skills/code-review"},
  {domain:"engineering",name:"debug",description:"Structured debugging session — reproduce, isolate, diagnose, and fix.",ref:"anthropics/knowledge-work-plugins/engineering/skills/debug"},
  {domain:"engineering",name:"deploy-checklist",description:"Pre-deployment verification checklist.",ref:"anthropics/knowledge-work-plugins/engineering/skills/deploy-checklist"},
  {domain:"engineering",name:"documentation",description:"Write and maintain technical documentation.",ref:"anthropics/knowledge-work-plugins/engineering/skills/documentation"},
  {domain:"engineering",name:"incident-response",description:"Run an incident response workflow — triage, communicate, and write postmortem.",ref:"anthropics/knowledge-work-plugins/engineering/skills/incident-response"},
  {domain:"engineering",name:"standup",description:"Generate a standup update from recent activity.",ref:"anthropics/knowledge-work-plugins/engineering/skills/standup"},
  {domain:"engineering",name:"system-design",description:"Design systems, services, and architectures.",ref:"anthropics/knowledge-work-plugins/engineering/skills/system-design"},
  {domain:"engineering",name:"tech-debt",description:"Identify, categorize, and prioritize technical debt.",ref:"anthropics/knowledge-work-plugins/engineering/skills/tech-debt"},
  {domain:"engineering",name:"testing-strategy",description:"Design test strategies and test plans.",ref:"anthropics/knowledge-work-plugins/engineering/skills/testing-strategy"},
  {domain:"productivity",name:"dashboard.html",description:"",ref:"anthropics/knowledge-work-plugins/productivity/skills/dashboard.html"},
  {domain:"productivity",name:"memory-management",description:"Two-tier memory system that makes Claude a true workplace collaborator. Decodes shorthand, acronyms, nicknames, and internal language so Claude understands requests like a colleague would. CLAUDE.md for working memory, m",ref:"anthropics/knowledge-work-plugins/productivity/skills/memory-management"},
  {domain:"productivity",name:"start",description:"Initialize the productivity system and open the dashboard.",ref:"anthropics/knowledge-work-plugins/productivity/skills/start"},
  {domain:"productivity",name:"task-management",description:"Simple task management using a shared TASKS.md file. Reference this when the user asks about their tasks, wants to add/complete tasks, or needs help tracking commitments.",ref:"anthropics/knowledge-work-plugins/productivity/skills/task-management"},
  {domain:"productivity",name:"update",description:"Sync tasks and refresh memory from your current activity.",ref:"anthropics/knowledge-work-plugins/productivity/skills/update"},
  {domain:"enterprise-search",name:"digest",description:"Generate a daily or weekly digest of activity across all connected sources.",ref:"anthropics/knowledge-work-plugins/enterprise-search/skills/digest"},
  {domain:"enterprise-search",name:"knowledge-synthesis",description:"Combines search results from multiple sources into coherent, deduplicated answers with source attribution. Handles confidence scoring based on freshness and authority, and summarizes large result sets effectively.",ref:"anthropics/knowledge-work-plugins/enterprise-search/skills/knowledge-synthesis"},
  {domain:"enterprise-search",name:"search-strategy",description:"Query decomposition and multi-source search orchestration. Breaks natural language questions into targeted searches per source, translates queries into source-specific syntax, ranks results by relevance, and handles ambi",ref:"anthropics/knowledge-work-plugins/enterprise-search/skills/search-strategy"},
  {domain:"enterprise-search",name:"search",description:"Search across all connected sources in one query.",ref:"anthropics/knowledge-work-plugins/enterprise-search/skills/search"},
  {domain:"enterprise-search",name:"source-management",description:"Manages connected MCP sources for enterprise search. Detects available sources, guides users to connect new ones, handles source priority ordering, and manages rate limiting awareness.",ref:"anthropics/knowledge-work-plugins/enterprise-search/skills/source-management"},
];

export const KNOWLEDGE_WORK_DOMAINS: string[] = [
  ...new Set(KNOWLEDGE_WORK_SKILLS.map((s) => s.domain)),
];
