// Bundle the published user-manual markdown (docs/src/content/docs/*.md) into a
// TS module the web app imports, so the in-app docs viewer ships the SAME
// content tied to the running version — no network, no drift. Re-run after
// editing the docs: `pnpm gen:docs` (also wired into prebuild). The source of
// truth stays the markdown files; this is a generated artifact.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "../../docs/src/content/docs");
const OUT = join(here, "../src/lib/docs-content.ts");

function frontmatterValue(fm, key) {
  const line = fm.split("\n").find((l) => l.startsWith(`${key}:`));
  if (!line) return "";
  let v = line.slice(key.length + 1).trim();
  if (
    (v.startsWith('"') && v.endsWith('"')) ||
    (v.startsWith("'") && v.endsWith("'"))
  ) {
    v = v.slice(1, -1);
  }
  return v;
}

function parse(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { title: "", description: "", body: md.trim() };
  return {
    title: frontmatterValue(m[1], "title"),
    description: frontmatterValue(m[1], "description"),
    body: m[2].trim(),
  };
}

const files = readdirSync(SRC)
  .filter((f) => f.endsWith(".md"))
  .sort();
const docs = {};
for (const f of files) {
  docs[f.replace(/\.md$/, "")] = parse(readFileSync(join(SRC, f), "utf8"));
}

const banner =
  "// AUTO-GENERATED by scripts/gen-docs.mjs from docs/src/content/docs/*.md.\n" +
  "// Do not edit by hand — edit the source markdown and run `pnpm gen:docs`.\n\n";
const body =
  "export type DocPage = { title: string; description: string; body: string };\n\n" +
  `export const DOCS: Record<string, DocPage> = ${JSON.stringify(docs, null, 2)};\n`;

writeFileSync(OUT, banner + body);
console.log(`gen-docs: wrote ${Object.keys(docs).length} pages → ${OUT}`);
