// Generates api/src/native_oauth_allowlist.rs from the MCP provider catalog.
//
// The Rust token-refresh path (api/src/native_oauth.rs) needs an origin
// allowlist — for each provider's MCP-server origin, the exact set of OAuth
// authorization-server origins it may advertise through protected-resource
// discovery. That data already lives in web/src/lib/mcp-providers.ts
// (mcpServerUrl + oauthAuthorizationServerOrigins), but the api crate can't
// import the TS catalog, so the Rust side used to keep a SECOND hand-written
// copy, guarded only by a drift-detecting vitest. This script eliminates that
// failure class: the Rust allowlist is now GENERATED from the catalog, and the
// vitest (mcp-providers.allowlist-sync.test.ts) fails only when the generated
// file is stale — the fix is always "regenerate", never "hand-sync two lists".
//
// Run from web/:  npm run gen:allowlist   (or: npx tsx scripts/gen-native-oauth-allowlist.ts)
//
// Deliberately NOT wired into the Next build: the output is committed source
// for a different crate, and regeneration should be an explicit, reviewable
// step (same convention as gen:docs).

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { MCP_PROVIDERS } from "../src/lib/mcp-providers";

export const GENERATED_FILE_REPO_PATH = "api/src/native_oauth_allowlist.rs";

/**
 * Pure projection of the catalog into the generated Rust source. Exported so
 * the allowlist-sync vitest can compare this exact string against the file on
 * disk (staleness check) without touching the filesystem for the "expected"
 * side.
 */
export function renderNativeOauthAllowlistRs(): string {
  // (mcp-server origin → allowed OAuth origins), in catalog order. Skips
  // providers with no fixed MCP URL (self-key / instance-based) and providers
  // with no OAuth origins (pat) — they never hit the OAuth refresh path.
  const entries: { slug: string; mcpOrigin: string; oauthOrigins: string[] }[] = [];
  const byOrigin = new Map<string, { slug: string; oauthOrigins: string[] }>();

  for (const provider of Object.values(MCP_PROVIDERS)) {
    if (!provider.mcpServerUrl) continue;
    if (provider.oauthAuthorizationServerOrigins.length === 0) continue;

    const mcpOrigin = new URL(provider.mcpServerUrl).origin;
    const oauthOrigins = [...new Set(provider.oauthAuthorizationServerOrigins)];

    for (const origin of [mcpOrigin, ...oauthOrigins]) {
      if (!origin.startsWith("https://")) {
        throw new Error(
          `${provider.slug}: non-https origin ${JSON.stringify(origin)} — ` +
            `the Rust refresher only trusts https origins.`,
        );
      }
      if (new URL(origin).origin !== origin) {
        throw new Error(
          `${provider.slug}: ${JSON.stringify(origin)} is not a bare origin ` +
            `(has a path, trailing slash, or default port).`,
        );
      }
    }

    const dup = byOrigin.get(mcpOrigin);
    if (dup) {
      // Two providers sharing an MCP origin must agree on the allowed OAuth
      // origins, otherwise the (origin-keyed) Rust lookup is ambiguous.
      const same =
        JSON.stringify([...dup.oauthOrigins].sort()) ===
        JSON.stringify([...oauthOrigins].sort());
      if (!same) {
        throw new Error(
          `MCP origin ${mcpOrigin} is claimed by both "${dup.slug}" and ` +
            `"${provider.slug}" with different OAuth origins — the allowlist ` +
            `is keyed by origin, so these must match.`,
        );
      }
      continue; // identical duplicate: first entry already covers it
    }

    byOrigin.set(mcpOrigin, { slug: provider.slug, oauthOrigins });
    entries.push({ slug: provider.slug, mcpOrigin, oauthOrigins });
  }

  const tuples = entries
    .map(
      (e) =>
        `    ("${e.mcpOrigin}", &[${e.oauthOrigins
          .map((o) => `"${o}"`)
          .join(", ")}]), // ${e.slug}\n`,
    )
    .join("");

  return `\
// @generated by web/scripts/gen-native-oauth-allowlist.ts — DO NOT EDIT BY HAND.
//
// Source of truth: web/src/lib/mcp-providers.ts (MCP_PROVIDERS). Each tuple is
// (MCP-server origin, exact OAuth authorization-server origins that provider
// may advertise through /.well-known/oauth-protected-resource). The refresh
// path in native_oauth.rs aborts when a discovered endpoint's origin is not in
// this list — see the Dialed regression for why.
//
// Regenerate after ANY catalog change that touches mcpServerUrl or
// oauthAuthorizationServerOrigins:
//
//     cd web && npm run gen:allowlist
//
// CI enforcement: web/src/lib/mcp-providers.allowlist-sync.test.ts fails when
// this file is stale.

#[rustfmt::skip]
pub(crate) const NATIVE_MCP_OAUTH_ALLOWLIST: &[(&str, &[&str])] = &[
${tuples}];
`;
}

// Write the file when executed directly (not when imported by the vitest).
const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, "..", "..", GENERATED_FILE_REPO_PATH);
  writeFileSync(outPath, renderNativeOauthAllowlistRs());
  console.log(`wrote ${outPath}`);
}
